// @ts-check
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import tailwindcss from "@tailwindcss/vite";
import okfTarball from "./astro-okf-tarball.mjs";

const SITE = "https://specification.website";

// Sitemaps are generated by per-category endpoints under src/pages/sitemap-*.xml.ts
// instead of @astrojs/sitemap, so each category gets its own file and the index
// can be reported on separately in Search Console.

// https://astro.build/config
export default defineConfig({
  site: SITE,
  integrations: [mdx(), okfTarball()],
  vite: {
    plugins: [tailwindcss()],
  },
  server: {
    port: 31337,
    host: true,
  },
  markdown: {
    shikiConfig: {
      // Dual themes emit per-token --shiki-light / --shiki-dark CSS variables
      // instead of baking one theme's colours inline. global.css then selects
      // between them with light-dark(), so code blocks follow the same
      // OS-default + [data-theme] override mechanism as the rest of the site.
      themes: {
        light: "github-light-default",
        dark: "github-dark-default",
      },
      defaultColor: false,
      wrap: true,
    },
  },
  build: {
    inlineStylesheets: "auto",
  },
});
